import CartSection from '@/components/cart/CartSection'
import Copyright from '@/components/shared/Copyright'
import Footer from '@/components/shared/Footer'
import Logo from '@/components/shared/Logo'
import Navbar from '@/components/shared/Navbar'
import Search from '@/components/shared/Search'
import CartProvider from '@/provider/CartProvider'
import connectMongo from '@/services/connectMongo'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ecommerce - LWSKart',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  await connectMongo()
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <header className="py-4 shadow-sm bg-white">
            <div className="container flex items-center justify-between">
              <Logo />
              <Search />
              <CartSection />
            </div>
          </header>
          <Navbar />
          {children}
          <div id="modal-root-content" />
          <Footer />
          <Copyright />
        </CartProvider>
      </body>
    </html>
  )
}
