import Cart from '@/components/shared/Cart'
import Copyright from '@/components/shared/Copyright'
import Footer from '@/components/shared/Footer'
import Logo from '@/components/shared/Logo'
import Navbar from '@/components/shared/Navbar'
import Search from '@/components/shared/Search'
import { Inter } from 'next/font/google'
import './globals.css'
import connectMongo from '@/services/connectMongo'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ecommerce - LWSKart',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  await connectMongo()
  return (
    <html lang="en">
      <body className={inter.className}>
        <header class="py-4 shadow-sm bg-white">
          <div class="container flex items-center justify-between">
            <Logo />
            <Search />
            <Cart />
          </div>
        </header>
        <Navbar />
        {children}
        <Footer />
        <Copyright />
      </body>
    </html>
  )
}
