import Copyright from "@/components/shared/Copyright";
import Footer from "@/components/shared/Footer";
import CartProvider from "@/provider/CartProvider";
import ToastProvider from "@/provider/ToastProvider";
import connectMongo from "@/backend/services/connectMongo";
import { Inter } from "next/font/google";
import "../globals.css";
import ThemeProvider from "@/provider/ThemeProvider";
import HeaderSection from "@/components/header/HeaderSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce - LWSKart",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { lang } }) {
  await connectMongo();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <CartProvider>
            <ToastProvider>
              <main className="dark:bg-body dark:text-white">
                <HeaderSection lang={lang} />
                {children}
                <div id="modal-root-content" />
                <Footer />
              </main>
              <Copyright />
            </ToastProvider>
          </CartProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
